import { Product } from "../types/product";

export const products: Product[] = [
  {
    id: "63843724-0bec-4b9c-b312-adab433d31c5",
    name: "Cureline Powder",
    brand: "Keypharma",
    category: "Pain Relief & Anti-inflammatory",
    description:
      "Premium pain relief powder with advanced anti-inflammatory agents. Trusted by healthcare professionals for fast-acting relief.",
    price: 25.64,
    stock: 174,
    rating: 3.9,
    tags: ["pain", "fast-acting", "pharmacy"],
    image_urls: "/5.webp",
    created_at: "2025-10-10T20:26:27.606177",
    specs: {
      "Active Ingredient": "Ibuprofen 400mg",
      Quantity: "100 sachets",
      Dosage: "1 sachet per 4 hours",
      Storage: "Room temperature",
    },
    reviews: [
      { author: "Sarah M.", rating: 4, comment: "Great for quick pain relief" },
      { author: "John D.", rating: 4, comment: "Works well, good price" },
    ],
  },
  {
    id: "625e6ad8-a1e2-4bce-89d1-c440b39c2183",
    name: "HealthSure Syrup",
    brand: "Healix",
    category: "Pain Relief & Anti-inflammatory",
    description:
      "A high-quality pain relief & anti-inflammatory product formulated for optimal health and wellness.",
    price: 57.64,
    stock: 74,
    rating: 4.5,
    tags: ["pain", "health", "pharmacy"],
    image_urls: "/5.webp",
    created_at: "2025-10-10T20:26:27.606273",
    specs: {
      "Active Ingredient": "Paracetamol 250mg/5ml",
      Form: "Liquid Syrup",
      Quantity: "200ml",
      Dosage: "5-10ml every 4-6 hours",
      "Age Group": "Children & Adults",
      Storage: "Keep below 25°C, shake well before use",
    },
    reviews: [
      {
        author: "Emma L.",
        rating: 5,
        comment: "Fast-acting and easy to take for kids",
      },
      {
        author: "Michael R.",
        rating: 4,
        comment: "Good quality syrup, pleasant taste",
      },
      {
        author: "Lisa W.",
        rating: 4,
        comment: "Works well for fever reduction",
      },
    ],
  },
  {
    id: "648a3228-e3ad-4044-a538-5ba61749df45",
    name: "MediCore Capsules",
    brand: "PharmEase",
    category: "Pain Relief & Anti-inflammatory",
    description:
      "A high-quality pain relief & anti-inflammatory product formulated for optimal health and wellness.",
    price: 46.24,
    stock: 274,
    rating: 4.6,
    tags: ["pain", "health", "pharmacy"],
    image_urls: "/5.webp",
    created_at: "2025-10-10T20:26:27.606376",
    specs: {
      "Active Ingredient": "Naproxen 250mg",
      Form: "Hard Gelatin Capsules",
      Quantity: "30 capsules per pack",
      Dosage: "1 capsule twice daily with food",
      Strength: "250mg",
      "Shelf Life": "3 years",
      Storage: "Room temperature, away from moisture",
    },
    reviews: [
      {
        author: "David K.",
        rating: 5,
        comment: "Excellent for arthritis pain",
      },
      {
        author: "Patricia M.",
        rating: 4,
        comment: "Long-lasting relief, very effective",
      },
      {
        author: "Robert T.",
        rating: 5,
        comment: "Best capsule formulation I've tried",
      },
    ],
  },
  {
    id: "077bcbb3-4dc9-4cb5-b0fd-65eab605902d",
    name: "MediCore Gel",
    brand: "NeoHealth",
    category: "Pain Relief & Anti-inflammatory",
    description:
      "A high-quality pain relief & anti-inflammatory product formulated for optimal health and wellness.",
    price: 39.85,
    stock: 119,
    rating: 4.6,
    tags: ["pain", "health", "pharmacy"],
    image_urls: "/5.webp",
    created_at: "2025-10-10T20:26:27.606448",
    specs: {
      "Active Ingredient": "Diclofenac Sodium 1%",
      Form: "Topical Gel",
      Quantity: "100g tube",
      Application: "Apply to affected area, massage gently",
      Frequency: "2-3 times daily",
      "Onset Time": "15-30 minutes",
      Storage: "Keep in cool, dry place",
    },
    reviews: [
      {
        author: "Catherine B.",
        rating: 5,
        comment: "Great for muscle pain and strains",
      },
      {
        author: "George H.",
        rating: 4,
        comment: "Easy to apply, effective relief",
      },
      {
        author: "Sandra P.",
        rating: 5,
        comment: "Works wonderfully for joint pain",
      },
    ],
  },
  {
    id: "755744ed-1e21-4f52-852b-807be50e81db",
    name: "Keypharma Gel",
    brand: "VitaPlus",
    category: "Pain Relief & Anti-inflammatory",
    description:
      "A high-quality pain relief & anti-inflammatory product formulated for optimal health and wellness.",
    price: 16.16,
    stock: 444,
    rating: 4.6,
    tags: ["pain", "health", "pharmacy"],
    image_urls: "/5.webp",
    created_at: "2025-10-10T20:26:27.606475",
    specs: {
      "Active Ingredient": "Methyl Salicylate 10%",
      Form: "Warming Gel",
      Quantity: "75g tube",
      Application: "Apply and massage into skin",
      Frequency: "2-4 times daily as needed",
      Feeling: "Warming sensation for 30+ minutes",
      Storage: "Below 30°C, keep lid tight",
    },
    reviews: [
      {
        author: "Vincent C.",
        rating: 4,
        comment: "Nice warming effect, very affordable",
      },
      { author: "Diana S.", rating: 4, comment: "Good for muscle tension" },
      { author: "Mark N.", rating: 5, comment: "Best budget option available" },
    ],
  },
  {
    id: "76b96735-0f52-41d5-872e-eea4f2546774",
    name: "Keypharma Monitor",
    brand: "BioCare",
    category: "Pain Relief & Anti-inflammatory",
    description:
      "A high-quality pain relief & anti-inflammatory product formulated for optimal health and wellness.",
    price: 31.4,
    stock: 132,
    rating: 4.6,
    tags: ["pain", "health", "pharmacy"],
    image_urls: "/5.webp",
    created_at: "2025-10-10T20:26:27.606494",
    specs: {
      "Active Ingredient": "Ibuprofen 200mg",
      Form: "Tablet",
      Quantity: "50 tablets per pack",
      Dosage: "1-2 tablets every 4-6 hours",
      "Max Daily Dose": "6 tablets (1200mg)",
      Onset: "30-45 minutes",
      Storage: "Room temperature, away from light",
    },
    reviews: [
      {
        author: "Paul H.",
        rating: 5,
        comment: "Reliable pain relief every time",
      },
      {
        author: "Jennifer M.",
        rating: 4,
        comment: "Good quality at competitive price",
      },
      {
        author: "Christopher L.",
        rating: 5,
        comment: "My go-to for everyday pain management",
      },
    ],
  },
  {
    id: "ff0fe989-ab6a-4c6a-83c4-7853904938de",
    name: "MediCore Spray",
    brand: "PharmEase",
    category: "Pain Relief & Anti-inflammatory",
    description:
      "A high-quality pain relief & anti-inflammatory product formulated for optimal health and wellness.",
    price: 39.56,
    stock: 284,
    rating: 4.9,
    tags: ["pain", "health", "pharmacy"],
    image_urls: "/5.webp",
    created_at: "2025-10-10T20:26:27.606512",
    specs: {
      "Active Ingredient": "Butyl Nicotinate 1% + Salicylic Acid 3%",
      Form: "Topical Spray",
      Quantity: "200ml aerosol can",
      Application: "Spray directly on affected area",
      Frequency: "3-4 times daily or as needed",
      "Heating Strength": "Mild to moderate warming",
      Storage: "Store at room temperature, away from heat sources",
    },
    reviews: [
      {
        author: "Michelle Y.",
        rating: 5,
        comment: "Best spray formula I've used, very convenient",
      },
      {
        author: "Richard T.",
        rating: 5,
        comment: "Fast-acting and effective spray delivery",
      },
      {
        author: "Susan G.",
        rating: 5,
        comment: "Excellent for sports-related pain",
      },
    ],
  },
];
